name: ifcbnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-lightning
  - Pillow
  - scikit-learn
  - scikit-image
  - pandas
  - h5py
  - scipy<1.9.2
  - numpy
  - pyyaml
  - requests
  - rectpack
  - pysmb
  - pip
  - pip:
    - git+https://github.com/joefutrelle/pyifcb.git
