name: ifcbnn
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - pandas
  - scipy
  - numpy
  - h5py
  - pip
- pip:
  - git+https://github.com/joefutrelle/pyifcb.git
