name: ifcbnn-legacy
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pytorch=1.7.1
  - torchvision=0.8.2
  - torchmetrics=0.6.0
  - pytorch-lightning=1.3.8
  - onnxruntime=1.7.2
  - scikit-learn=1.0.2
  - scikit-image=0.19.3
  - numpy=1.21.6
  - scipy=1.7.3
  - pandas=1.3.5
  - h5py=3.6.0
  - rectpack
  - pysmb
  - pip
- pip:
  - ../pyifcb
